# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowcal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogCal(object):
    def setupUi(self, DialogCal):
        DialogCal.setObjectName("DialogCal")
        DialogCal.resize(312, 183)
        self.calendar = QtWidgets.QCalendarWidget(DialogCal)
        self.calendar.setGeometry(QtCore.QRect(0, 0, 312, 183))
        self.calendar.setObjectName("calendar")

        self.retranslateUi(DialogCal)
        QtCore.QMetaObject.connectSlotsByName(DialogCal)

    def retranslateUi(self, DialogCal):
        _translate = QtCore.QCoreApplication.translate
        DialogCal.setWindowTitle(_translate("DialogCal", "Calendario"))
